export * from './About/About'
export * from './Education/Education'
export * from './Experience/Experience'
export * from './More/More'
export * from './Person/Person'
export * from './Toggle/Toggle'
export * from './Skills/Skills'
export * from './ToggleTwo/ToggleTwo'